FROM google/cloud-sdk:379.0.0-slim

RUN apt-get update
RUN apt-get install --yes software-properties-common
RUN apt-add-repository 'deb http://security.debian.org/debian-security stretch/updates main'
RUN apt-get update
RUN apt-get install --yes openjdk-8-jdk ant git dos2unix wget sed
RUN apt-get install --yes python3
RUN apt-get install --yes google-cloud-sdk-app-engine-java
RUN apt-get install --yes libc6 zlib1g libstdc++6 lib32z1

RUN update-java-alternatives -s java-1.8.0-openjdk-amd64

WORKDIR /home/punya
COPY ./ .

RUN git submodule update --init
RUN dos2unix ./docker-run.sh
RUN dos2unix ./buildtools
RUN ./buildtools doctor

WORKDIR /home/punya/appinventor
RUN ant MakeAuthKey 
RUN ant; exit 0
RUN sed -i -z 's/@DefaultMessage("Name")\n  @Description("")\n  String nameParams();\n\n  @DefaultMessage("Title")\n  @Description("")\n  String titleParams();//' /home/punya/appinventor/build/components/ComponentTranslation/src/com/google/appinventor/client/AutogeneratedOdeMessages.java
RUN ant

CMD /home/punya/docker-run.sh